global:
  scrape_interval: 15s

scrape_configs:
  - job_name: booking-api
    metrics_path: /metrics
    static_configs:
      - targets: ["booking-api:8000"]

  - job_name: cadvisor
    static_configs:
      - targets: ["cadvisor:8080"]
