env:
  REGISTRY: ghcr.io
  IMAGE_SUFFIX: booking-api-booking-api   # tên image bạn muốn sau owner/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute lowercase image name
        id: img
        run: |
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo "image=${{ env.REGISTRY }}/${OWNER_LC}/${{ env.IMAGE_SUFFIX }}" >> $GITHUB_OUTPUT

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: ./services/booking-api
          file: ./services/booking-api/Dockerfile
          push: true
          tags: |
            ${{ steps.img.outputs.image }}:latest
            ${{ steps.img.outputs.image }}:${{ github.sha }}
